<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>InfraControl.Agent.Service</RootNamespace>
    <AssemblyName>InfraControl.Agent.Service</AssemblyName>
    <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == ''">win-x64</RuntimeIdentifier>
    <PublishSingleFile Condition="'$(Configuration)' == 'Release'">true</PublishSingleFile>
    <SelfContained Condition="'$(Configuration)' == 'Release'">true</SelfContained>
    <UseAppHost>true</UseAppHost>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\InfraControl.Agent.Core\InfraControl.Agent.Core.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" />
    <PackageReference Include="Microsoft.Extensions.Logging.EventLog" />
  </ItemGroup>
</Project>
